"""
Django settings for extensionsys project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kq-9=)j-)1fy^s3429gjf@foaz@#wsx(v%ww$x+)%==0dpcyv='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '127.0.0.1:8000']


# Application definition

INSTALLED_APPS = [
    'crispy_forms',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_extensions',
    'bootstrap_modal_forms',
    'ckeditor',
    'apps.base',
    'apps.blog',
    'apps.registrations',
    'apps.workshop',
    'users',
    'django_cleanup.apps.CleanupConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_auto_logout.middleware.auto_logout',
]

ROOT_URLCONF = 'extensionsys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates/',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
                'apps.workshop.context_processors.workshop_list_renderer',
                'apps.workshop.context_processors.workshop_facilitator_list_renderer',
                'apps.workshop.context_processors.workshop_participant_renderer',
                'apps.workshop.context_processors.lesson_list_renderer',
                'apps.workshop.context_processors.lessonfile_list_renderer',
                'apps.workshop.context_processors.activity_output_list_renderer',
            ],
        },
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(minutes=30),
    'SESSION_TIME': timedelta(minutes=120),
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}

WSGI_APPLICATION = 'extensionsys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'extensionsys',
        'USER': 'root',
        'PASSWORD': 'Rosales#2000',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'registrations.User'

USERS_VERIFY_EMAIL = False

USERS_AUTO_LOGIN_ON_ACTIVATION = True

USERS_EMAIL_CONFIRMATION_TIMEOUT_DAYS = 3

USERS_SPAM_PROTECTION = True

USERS_REGISTRATION_OPEN = True

# Specifies minimum length for passwords:
USERS_PASSWORD_MIN_LENGTH = 6

#Specifies maximum length for passwords:
USERS_PASSWORD_MAX_LENGTH = None

USERS_CHECK_PASSWORD_COMPLEXITY = True

USERS_PASSWORD_POLICY = {
        'UPPER': 1,       # Uppercase 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        'LOWER': 1,       # Lowercase 'abcdefghijklmnopqrstuvwxyz'
        'DIGITS': 1,      # Digits '0123456789'
        'PUNCTUATION': 1  # Punctuation """!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""
}

USERS_VALIDATE_EMAIL_DOMAIN = True

USERS_EMAIL_DOMAINS_WHITELIST = ['carsu.edu.ph']

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_DIRS = (
    './static',
)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login'

CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'width': 'auto',
    },
}

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "ESP Dashboard",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "ESP Dashboard",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Extension Services Program",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "base/img/favicon-32x32.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "base/img/favicon-32x32.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the ESP Dashboard",

    # Copyright on the footer
    "copyright": "CCIS Extension Services Program",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "auth.User",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,
}

JAZZMIN_SETTINGS["show_ui_builder"] = True

JAZZMIN_UI_TWEAKS = {
    "brand_small_text": True,
    "accent": "accent-dark",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-info",
        "info": "btn-success",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-primary",
    },
}